[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  # Increase Node.js memory limit for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Authentication redirects
[[redirects]]
  from = "/"
  to = "/auth/login"
  status = 302
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302
  conditions = {Role = ["authenticated"]}

# Redirect old routes (if any)
[[redirects]]
  from = "/clients/*"
  to = "/dashboard/clients/:splat"
  status = 301

[[redirects]]
  from = "/invoices/*"
  to = "/dashboard/invoices/:splat"
  status = 301

# Fallback for SPA routes
