# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

# Production context
[context.production]
  command = "npm install && npm run build"
  
[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Branch deploys (staging)
[context.deploy-preview]
  command = "npm install && npm run build"
  
[context.branch-deploy]
  command = "npm install && npm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
